# Data Analysis

**Part C:** **One-Hot Encoding For Categorical Variables**

Converting categorical variables Fuel_Type and Transmission to numerical form using one-hot encoding.

In [30]:
import pandas as pd
data = pd.read_csv("/content/clean_data.csv",index_col=0)
data

# Converting categorical variables 'Fuel_Type' and 'Transmission' into one-hot encoded columns
data = pd.get_dummies(data, columns=['Fuel_Type', 'Transmission'], drop_first=True)
print(data.head(20))

                                                Name    Location  Year  \
1                   Hyundai Creta 1.6 CRDi SX Option        Pune  2015
2                                       Honda Jazz V     Chennai  2011
3                                  Maruti Ertiga VDI     Chennai  2012
4                    Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013
6                             Nissan Micra Diesel XV      Jaipur  2013
7                  Toyota Innova Crysta 2.8 GX AT 8S      Mumbai  2016
8                Volkswagen Vento Diesel Comfortline        Pune  2013
9                     Tata Indica Vista Quadrajet LS     Chennai  2012
10                                  Maruti Ciaz Zeta       Kochi  2018
11                       Honda City 1.5 V AT Sunroof     Kolkata  2012
12                             Maruti Swift VDI BSIV      Jaipur  2015
13                  Land Rover Range Rover 2.2L Pure       Delhi  2014
14                    Land Rover Freelander 2 TD4 SE        Pune  2012
15                       Mitsubishi Pajero Sport 4X4       Delhi  2014
16                             Honda Amaze S i-Dtech       Kochi  2016
17                             Maruti Swift DDiS VDI      Jaipur  2017
18               Renault Duster 85PS Diesel RxL Plus       Kochi  2014
19  Mercedes-Benz New C-Class C 220 CDI BE Avantgare   Bangalore  2014
20                                 BMW 3 Series 320d       Kochi  2014
21                     Maruti S Cross DDiS 200 Alpha   Bangalore  2015

    Kilometers_Driven Owner_Type  Mileage  Engine   Power  Seats  Price  \
1               41000      First    19.67  1582.0  126.20    5.0  12.50
2               46000      First    13.00  1199.0   88.70    5.0   4.50
3               87000      First    20.77  1248.0   88.76    7.0   6.00
4               40670     Second    15.20  1968.0  140.80    5.0  17.74
6               86999      First    23.08  1461.0   63.10    5.0   3.50
7               36000      First    11.36  2755.0  171.50    8.0  17.50
8               64430      First    20.54  1598.0  103.60    5.0   5.20
9               65932     Second    22.30  1248.0   74.00    5.0   1.95
10              25692      First    21.56  1462.0  103.25    5.0   9.95
11              60000      First    16.80  1497.0  116.30    5.0   4.49
12              64424      First    25.20  1248.0   74.00    5.0   5.60
13              72000      First    12.70  2179.0  187.70    5.0  27.00
14              85000     Second     0.00  2179.0  115.00    5.0  17.50
15             110000      First    13.50  2477.0  175.56    7.0  15.00
16              58950      First    25.80  1498.0   98.60    5.0   5.40
17              25000      First    28.40  1248.0   74.00    5.0   5.99
18              77469      First    20.45  1461.0   83.80    5.0   6.34
19              78500      First    14.84  2143.0  167.62    5.0  28.00
20              32982      First    22.69  1995.0  190.00    5.0  18.55
21              55392     Second    23.65  1248.0   88.50    5.0   8.25

    Fuel_Type_Electric  Fuel_Type_Petrol  Transmission_Manual
1                False             False                 True
2                False              True                 True
3                False             False                 True
4                False             False                False
6                False             False                 True
7                False             False                False
8                False             False                 True
9                False             False                 True
10               False              True                 True
11               False              True                False
12               False             False                 True
13               False             False                False
14               False             False                False
15               False             False                 True
16               False             False                 True
17               False             False                 True
18               False             False                 True
19               False             False                False
20               False             False                False
21               False             False                 True

**Part D:** Adding a new feature Car_Age

Calculate the current age of each car by subtracting the Year from the current year.

In [31]:
from datetime import datetime

# Calculate the current age of the car by subtracting the 'Year' from the current year
current_year = datetime.now().year
data['Car_Age'] = current_year - data['Year']
data[['Year', 'Car_Age']].head()

   Year  Car_Age
1  2015        9
2  2011       13
3  2012       12
4  2013       11
6  2013       11

**Part E:** Data Manipulation and Operations (Select, Filter, Rename, Mutate, Arrange, Summarize)

In [32]:
# Select specific columns
selected_data = data[['Name', 'Location', 'Car_Age', 'Price']]
selected_data.head()

                               Name    Location  Car_Age  Price
1  Hyundai Creta 1.6 CRDi SX Option        Pune        9  12.50
2                      Honda Jazz V     Chennai       13   4.50
3                 Maruti Ertiga VDI     Chennai       12   6.00
4   Audi A4 New 2.0 TDI Multitronic  Coimbatore       11  17.74
6            Nissan Micra Diesel XV      Jaipur       11   3.50

In [33]:
# Filter rows where Price is greater than 10 (in lakhs)
filtered_data = data[data['Price'] > 10]
filtered_data.head()

,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.2,5.0,12.50,False,False,True,9
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.8,5.0,17.74,False,False,False,11
7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,First,11.36,2755.0,171.5,8.0,17.50,False,False,False,8
13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,First,12.70,2179.0,187.7,5.0,27.00,False,False,False,10
14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Second,0.00,2179.0,115.0,5.0,17.50,False,False,False,12

In [34]:
# Rename column (e.g., 'Power' to 'Horse_Power')
data.rename(columns={'Power': 'Horse_Power'}, inplace=True)
data.head()

,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Horse_Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,12.50,False,False,True,9
2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199.0,88.70,5.0,4.50,False,True,True,13
3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,6.00,False,False,True,12
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,17.74,False,False,False,11
6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,3.50,False,False,True,11

In [36]:
# Arrange data by 'Price' in descending order
arranged_data = data.sort_values(by='Price', ascending=False)
arranged_data.head()

,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Horse_Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
4079,Land Rover Range Rover 3.0 Diesel LWB Vogue,Hyderabad,2017,25000,First,13.33,2993.0,255.0,5.0,160.00,False,False,False,7
5781,Lamborghini Gallardo Coupe,Delhi,2011,6500,Third,6.40,5204.0,560.0,2.0,120.00,False,True,False,13
5919,Jaguar F Type 5.0 V8 S,Hyderabad,2015,8000,First,12.50,5000.0,488.1,2.0,100.00,False,True,False,9
1505,Land Rover Range Rover Sport SE,Kochi,2019,26013,First,12.65,2993.0,255.0,5.0,97.07,False,False,False,5
1974,BMW 7 Series 740Li,Coimbatore,2018,28060,First,12.05,2979.0,320.0,5.0,93.67,False,True,False,6

In [37]:
# Summarize average price by location using groupby
average_price_by_location = data.groupby('Location')['Price'].mean().reset_index()
average_price_by_name = data.groupby('Name')['Price'].mean().reset_index()
print(average_price_by_name.head(20))

                                             Name      Price
0                  Ambassador Classic Nova Diesel   1.350000
1                       Audi A3 35 TDI Attraction  16.500000
2                          Audi A3 35 TDI Premium  19.250000
3                     Audi A3 35 TDI Premium Plus  18.900000
4                       Audi A3 35 TDI Technology  22.500000
5                                Audi A4 1.8 TFSI   9.000000
6             Audi A4 1.8 TFSI Technology Edition  17.500000
7                                 Audi A4 2.0 TDI  15.175882
8            Audi A4 2.0 TDI 177 Bhp Premium Plus  20.030000
9      Audi A4 2.0 TDI 177 Bhp Technology Edition  25.500000
10            Audi A4 2.0 TDI Celebration Edition   9.750000
11                    Audi A4 2.0 TDI Multitronic  14.773000
12  Audi A4 2.0 TDI Premium Sport Limited Edition  24.630000
13                               Audi A4 2.0 TFSI  12.000000
14                        Audi A4 3.0 TDI Quattro  24.760000
15                Audi A4 3.0 TDI Quattro Premium  12.955000
16                   Audi A4 30 TFSI Premium Plus  21.730000
17                         Audi A4 35 TDI Premium  24.980000
18                    Audi A4 35 TDI Premium Plus  20.850000
19                   Audi A4 35 TDI Premium Sport  28.000000

In [28]:
average_price_by_location.head(20)

      Location  Car_Price
0    Ahmedabad   8.567248
1    Bangalore  13.482670
2      Chennai   7.958340
3   Coimbatore  15.160206
4        Delhi   9.881944
5    Hyderabad   9.997423
6       Jaipur   5.916725
7        Kochi  11.309109
8      Kolkata   5.733924
9       Mumbai   9.592546
10        Pune   6.951000